#!/bin/bash

. resolve

docker build -t aerospike/aerospike-server-enterprise:${VERSION:-latest} .

if [ $PUSH ] && [ $PUSH -eq 1 ]; then
  docker push aerospike/aerospike-server-enterprise:${VERSION:-latest}
fi
