#!/bin/bash

. resolve

docker build -t ${REPO:+$REPO/}aerospike/server-enterprise:${VERSION:-latest} .

if [ $REPO ]; then
  docker push ${REPO:+$REPO/}aerospike/server-enterprise:${VERSION:-latest}
fi
