name: reviewdog
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
          filter_mode: file
          fail_on_error: true

  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning
          filter_mode: file
          fail_on_error: true

  shfmt:
    name: runner / shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-shfmt@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          shfmt_flags: ''
          level: warning
          filter_mode: file
          fail_on_error: true

  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-hadolint@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          filter_mode: file
          fail_on_error: true

  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          reporter: "github-check" # doesn't work well with review
          level: warning
          filter_mode: file
          fail_on_error: true
          markdownlint_flags: "--disable line_length"
